// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RulesScoringAndReferralMatrix.Data;

#nullable disable

namespace RulesScoringAndReferralMatrix.Migrations
{
    [DbContext(typeof(RulesScoringAndReferralMatrixDbContext))]
    [Migration("20260519153523_RemoveReferralMatrixAndReferrals")]
    partial class RemoveReferralMatrixAndReferrals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RulesScoringAndReferralMatrix.Models.RiskScore", b =>
                {
                    b.Property<Guid>("RiskScoreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Band")
                        .HasColumnType("int");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ScoreValue")
                        .HasColumnType("float");

                    b.Property<DateTime>("ScoredDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubmissionID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RiskScoreID");

                    b.ToTable("RiskScores");
                });

            modelBuilder.Entity("RulesScoringAndReferralMatrix.Models.UWRule", b =>
                {
                    b.Property<Guid>("UWRuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpressionJSON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("UWRuleID");

                    b.ToTable("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
