// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RulesScoringAndReferralMatrix.Data;

#nullable disable

namespace RulesScoringAndReferralMatrix.Migrations
{
    [DbContext(typeof(RulesScoringAndReferralMatrixDbContext))]
    partial class RulesScoringAndReferralMatrixDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RulesScoringAndReferralMatrix.Models.Referral", b =>
                {
                    b.Property<Guid>("ReferralID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RaisedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequiredAuthority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("SubmissionID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReferralID");

                    b.ToTable("Referrals");
                });

            modelBuilder.Entity("RulesScoringAndReferralMatrix.Models.ReferralMatrix", b =>
                {
                    b.Property<Guid>("ReferralMatrixID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CriteriaJSON")
                        .HasColumnType("int");

                    b.Property<string>("ProductLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequiredAuthority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ReferralMatrixID");

                    b.ToTable("ReferralMatrices");
                });

            modelBuilder.Entity("RulesScoringAndReferralMatrix.Models.RiskScore", b =>
                {
                    b.Property<Guid>("RiskScoreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Band")
                        .HasColumnType("int");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ScoreValue")
                        .HasColumnType("float");

                    b.Property<DateTime>("ScoredDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubmissionID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RiskScoreID");

                    b.ToTable("RiskScores");
                });

            modelBuilder.Entity("RulesScoringAndReferralMatrix.Models.UWRule", b =>
                {
                    b.Property<Guid>("UWRuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExpressionJSON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("UWRuleID");

                    b.ToTable("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
