// <auto-generated />
using System;
using DistributionAndPartyManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DistributionAndPartyManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260415094638_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DistributionAndPartyManagement.Models.Entities.Agent", b =>
                {
                    b.Property<string>("AgentID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ProducerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AgentID");

                    b.HasIndex("Name");

                    b.HasIndex("ProducerCode")
                        .IsUnique();

                    b.HasIndex("Region");

                    b.HasIndex("Status");

                    b.ToTable("Agent", (string)null);

                    b.HasData(
                        new
                        {
                            AgentID = "AGT-20250101-0001",
                            ContactInfo = "Mumbai Office, Andheri West",
                            Name = "Rajesh Kumar",
                            ProducerCode = "MUM-LIF-001",
                            Region = "Mumbai",
                            Status = "Active"
                        },
                        new
                        {
                            AgentID = "AGT-20250101-0002",
                            ContactInfo = "Delhi Office, Connaught Place",
                            Name = "Priya Sharma",
                            ProducerCode = "DEL-PNC-002",
                            Region = "Delhi",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("DistributionAndPartyManagement.Models.Entities.CustomerParty", b =>
                {
                    b.Property<string>("PartyID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DOBIncorporation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PartyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PartyID");

                    b.HasIndex("Name");

                    b.HasIndex("PartyType");

                    b.HasIndex("Segment");

                    b.HasIndex("Status");

                    b.ToTable("CustomerParty", (string)null);

                    b.HasData(
                        new
                        {
                            PartyID = "PTY-20250101-0001",
                            ContactInfo = "Pune, Maharashtra",
                            DOBIncorporation = new DateTime(1985, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Amit Patel",
                            PartyType = "Individual",
                            Segment = "Retail",
                            Status = "Active"
                        },
                        new
                        {
                            PartyID = "PTY-20250101-0002",
                            ContactInfo = "Bangalore, Karnataka",
                            DOBIncorporation = new DateTime(2010, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "TechCorp Solutions Pvt Ltd",
                            PartyType = "Organization",
                            Segment = "SME",
                            Status = "Active"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
