// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PricingQuotationAndTerms.Infrastructure.Data;

#nullable disable

namespace PricingQuotationAndTerms.Migrations
{
    [DbContext(typeof(QuoteDbContext))]
    [Migration("20260521155144_AddCommercialAndPnCBaseRates")]
    partial class AddCommercialAndPnCBaseRates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PricingQuotationAndTerms.Domain.Entities.PricingParam", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ParamName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductLine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("ProductLine", "ParamName", "IsActive")
                        .HasDatabaseName("IX_PricingParams_ProductLine_ParamName_Active");

                    b.ToTable("PricingParams", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a8dd49ed-1842-99e3-bb44-2f323677faeb"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Motor: 2.5% per annum",
                            EffectiveFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ParamName = "BaseRate",
                            ProductLine = "Motor",
                            Value = 0.025m
                        },
                        new
                        {
                            Id = new Guid("fe0f55aa-0263-e1e5-eb4c-55bc0e8f5360"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Health: 3.5% per annum",
                            EffectiveFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ParamName = "BaseRate",
                            ProductLine = "Health",
                            Value = 0.035m
                        },
                        new
                        {
                            Id = new Guid("0c56ca4e-50bd-5715-b3f7-f639fdaf4f7c"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Property: 1.5% per annum",
                            EffectiveFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ParamName = "BaseRate",
                            ProductLine = "Property",
                            Value = 0.015m
                        },
                        new
                        {
                            Id = new Guid("aea3272e-e239-0285-f6fd-b9ef4b8ae1ca"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Life: 2.0% per annum",
                            EffectiveFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ParamName = "BaseRate",
                            ProductLine = "Life",
                            Value = 0.020m
                        },
                        new
                        {
                            Id = new Guid("efb4a3c9-6f1f-c8ea-9dbf-28be4adeb286"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "PnC: 2.2% per annum",
                            EffectiveFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ParamName = "BaseRate",
                            ProductLine = "PnC",
                            Value = 0.022m
                        },
                        new
                        {
                            Id = new Guid("f1d88bb2-77c0-8eb3-c589-2afed8bc33bd"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Commercial: 1.8% per annum",
                            EffectiveFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ParamName = "BaseRate",
                            ProductLine = "Commercial",
                            Value = 0.018m
                        },
                        new
                        {
                            Id = new Guid("948c0211-295d-c93d-8a39-21f537cd6a50"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "PnC floor premium: ₹750",
                            EffectiveFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ParamName = "MinimumPremium",
                            ProductLine = "PnC",
                            Value = 750m
                        },
                        new
                        {
                            Id = new Guid("ff347dfb-048a-72fa-0807-1ab7a01bf3c8"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Commercial floor premium: ₹1500",
                            EffectiveFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ParamName = "MinimumPremium",
                            ProductLine = "Commercial",
                            Value = 1500m
                        },
                        new
                        {
                            Id = new Guid("0f14bed1-46ea-bccb-b729-2d6df8e8e9a7"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "+10% for Medium risk band",
                            EffectiveFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ParamName = "RiskLoading_Medium",
                            ProductLine = "Global",
                            Value = 0.10m
                        },
                        new
                        {
                            Id = new Guid("aba95d6c-9030-c97c-f52c-0083177e5bcb"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "+25% for High risk band",
                            EffectiveFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ParamName = "RiskLoading_High",
                            ProductLine = "Global",
                            Value = 0.25m
                        },
                        new
                        {
                            Id = new Guid("21ade2e3-912c-1ff9-c4bb-9935a3cef11e"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mining: +30%",
                            EffectiveFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ParamName = "OccupationLoad_Mining",
                            ProductLine = "Global",
                            Value = 0.30m
                        },
                        new
                        {
                            Id = new Guid("273bd8e9-825d-152d-6c54-3a9edf33babe"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Construction: +20%",
                            EffectiveFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ParamName = "OccupationLoad_Construction",
                            ProductLine = "Global",
                            Value = 0.20m
                        },
                        new
                        {
                            Id = new Guid("0b9a7156-3edd-7f3c-b429-f763fb7a6c10"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Agriculture: +15%",
                            EffectiveFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ParamName = "OccupationLoad_Agriculture",
                            ProductLine = "Global",
                            Value = 0.15m
                        },
                        new
                        {
                            Id = new Guid("ea9c8223-a222-d5b9-6c28-e61b447a4ead"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Transport: +12%",
                            EffectiveFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ParamName = "OccupationLoad_Transport",
                            ProductLine = "Global",
                            Value = 0.12m
                        },
                        new
                        {
                            Id = new Guid("d3488aef-ae37-f866-2734-2ca22c5b4df4"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "IT: 0% (low risk)",
                            EffectiveFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ParamName = "OccupationLoad_IT",
                            ProductLine = "Global",
                            Value = 0.00m
                        },
                        new
                        {
                            Id = new Guid("7033ad09-0b4c-228b-f278-441dc87d8ec5"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Banking: 0% (low risk)",
                            EffectiveFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ParamName = "OccupationLoad_Banking",
                            ProductLine = "Global",
                            Value = 0.00m
                        },
                        new
                        {
                            Id = new Guid("cdccbf79-4f65-d06e-8f9a-a86cf5de5027"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Education: 0% (low risk)",
                            EffectiveFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ParamName = "OccupationLoad_Education",
                            ProductLine = "Global",
                            Value = 0.00m
                        },
                        new
                        {
                            Id = new Guid("19c49211-ed49-5d4e-a831-0b2cc1bcf955"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "3% discount for 12-month policy",
                            EffectiveFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ParamName = "TenureDiscount_12m",
                            ProductLine = "Global",
                            Value = 0.03m
                        },
                        new
                        {
                            Id = new Guid("7f259398-91b6-2a01-9f9b-32bac5ae13c1"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "5% discount for 24-month policy",
                            EffectiveFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ParamName = "TenureDiscount_24m",
                            ProductLine = "Global",
                            Value = 0.05m
                        },
                        new
                        {
                            Id = new Guid("b6304b58-5706-c9dc-e83a-e9d43f452e25"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "7% discount for 36-month policy",
                            EffectiveFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ParamName = "TenureDiscount_36m",
                            ProductLine = "Global",
                            Value = 0.07m
                        },
                        new
                        {
                            Id = new Guid("e325ee97-1b28-df21-4af9-97acbce5c115"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "2% discount via preferred agent",
                            EffectiveFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ParamName = "AgentDiscount_Preferred",
                            ProductLine = "Global",
                            Value = 0.02m
                        },
                        new
                        {
                            Id = new Guid("b5f7e7be-a834-5174-45b8-4661b17e74a9"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "5% loyalty discount for renewals",
                            EffectiveFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ParamName = "LoyaltyDiscount",
                            ProductLine = "Global",
                            Value = 0.05m
                        },
                        new
                        {
                            Id = new Guid("d94b7302-bd47-1880-8f91-b7f519ec212c"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "GST: 18% on adjusted premium",
                            EffectiveFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ParamName = "GstRate",
                            ProductLine = "Global",
                            Value = 0.18m
                        },
                        new
                        {
                            Id = new Guid("f70ba0e4-1bb2-d177-bd69-5cc2b210f368"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Floor premium: ₹500",
                            EffectiveFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ParamName = "MinimumPremium",
                            ProductLine = "Global",
                            Value = 500m
                        });
                });

            modelBuilder.Entity("PricingQuotationAndTerms.Domain.Entities.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("BasePremium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiscountsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("LoadingsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TaxesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("TermsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<decimal>("TotalPremium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Quotes_Status");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("IX_Quotes_SubmissionId");

                    b.ToTable("Quotes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
