// <auto-generated />
using System;
using ComplianceAuditAndQA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComplianceAuditAndQA.Migrations
{
    [DbContext(typeof(ComplianceDbContext))]
    partial class ComplianceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComplianceAuditAndQA.Models.AuthorityBreach", b =>
                {
                    b.Property<Guid>("BreachId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BreachType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("BreachId");

                    b.HasIndex("BreachType")
                        .HasDatabaseName("IX_AuthorityBreaches_BreachType");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_AuthorityBreaches_IsDeleted");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_AuthorityBreaches_Status");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("IX_AuthorityBreaches_SubmissionId");

                    b.ToTable("AuthorityBreaches", (string)null);
                });

            modelBuilder.Entity("ComplianceAuditAndQA.Models.ComplianceChecklist", b =>
                {
                    b.Property<Guid>("ChecklistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ChecklistId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_ComplianceChecklists_IsDeleted");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ComplianceChecklists_Status");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("IX_ComplianceChecklists_SubmissionId");

                    b.ToTable("ComplianceChecklists", (string)null);
                });

            modelBuilder.Entity("ComplianceAuditAndQA.Models.ExceptionLog", b =>
                {
                    b.Property<Guid>("ExceptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LoggedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Open");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ExceptionId");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_ExceptionLogs_Category");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_ExceptionLogs_IsDeleted");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ExceptionLogs_Status");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("IX_ExceptionLogs_SubmissionId");

                    b.ToTable("ExceptionLogs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
