// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReportingAndPortfolioAnalytics.Persistence;

#nullable disable

namespace ReportingAndPortfolioAnalytics.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    [Migration("20260428175657_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReportingAndPortfolioAnalytics.Domain.UWReport", b =>
                {
                    b.Property<Guid>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ReportID");

                    b.Property<string>("GeneratedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("GeneratedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("GeneratedDate");

                    b.Property<string>("MetricsJSON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Metrics");

                    b.Property<DateTime?>("PeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Scope");

                    b.Property<string>("ScopeValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ReportID");

                    b.HasIndex("GeneratedDate");

                    b.HasIndex("Scope");

                    b.HasIndex("Scope", "ScopeValue");

                    b.ToTable("UWReports");
                });
#pragma warning restore 612, 618
        }
    }
}
