// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RiskDataAndEvidence.Persistence;

#nullable disable

namespace RiskDataAndEvidence.Migrations
{
    [DbContext(typeof(RiskDataDbContext))]
    partial class RiskDataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RiskDataAndEvidence.Domain.EvidenceRef", b =>
                {
                    b.Property<Guid>("EvidenceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EvidenceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferenceNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResultJSON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("SubmissionID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EvidenceID");

                    b.HasIndex("SubmissionID");

                    b.HasIndex("SubmissionID", "EvidenceType");

                    b.ToTable("EvidenceRefs");
                });

            modelBuilder.Entity("RiskDataAndEvidence.Domain.RiskProfile", b =>
                {
                    b.Property<Guid>("RiskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttributesJSON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("RiskNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("RiskType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SubmissionID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RiskID");

                    b.HasIndex("RiskType");

                    b.HasIndex("SubmissionID");

                    b.ToTable("RiskProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
