using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NotificationsAndAlerts.Models.Entities
{
    public class Notification
    {
        // Format: NTF-yyyyMMdd-XXXX (generated by NotificationService)
        [Key]
        public string NotificationID { get; set; } = string.Empty;

        // Recipient — maps to legacy "UserID" column
        [Required]
        [Column("UserID")]
        public string Mail { get; set; } = string.Empty;

        // Creator of the notification
        [Required]
        public string SenderEmail { get; set; } = string.Empty;

        [Required]
        public string Message { get; set; } = string.Empty;

        // Referral / SLA / Subjectivity / Quote / Compliance
        [Required]
        public string Category { get; set; } = string.Empty;

        // Unread / Read / Dismissed
        [Required]
        public string Status { get; set; } = "Unread";

        public DateTime CreatedDate { get; set; } = DateTime.UtcNow;
    }
}
