// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationsAndAlerts.Data;

#nullable disable

namespace NotificationsAndAlerts.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NotificationsAndAlerts.Models.Entities.Notification", b =>
                {
                    b.Property<string>("NotificationID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NotificationID");

                    b.HasIndex("Category");

                    b.HasIndex("Status");

                    b.HasIndex("UserID");

                    b.ToTable("Notification", (string)null);

                    b.HasData(
                        new
                        {
                            NotificationID = "NTF-20260102-0001",
                            Category = "Referral",
                            CreatedDate = new DateTime(2026, 1, 2, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Message = "Submission SUB-2026-0042 has been referred for your review.",
                            Status = "Unread",
                            UserID = "USR-001"
                        },
                        new
                        {
                            NotificationID = "NTF-20260103-0001",
                            Category = "Quote",
                            CreatedDate = new DateTime(2026, 1, 3, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            Message = "Quote QT-2026-0099 has been generated and is awaiting customer acceptance.",
                            Status = "Read",
                            UserID = "USR-002"
                        },
                        new
                        {
                            NotificationID = "NTF-20260104-0001",
                            Category = "SLA",
                            CreatedDate = new DateTime(2026, 1, 4, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "SLA breach warning: case CASE-2026-0007 nearing 24-hour deadline.",
                            Status = "Unread",
                            UserID = "USR-001"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
